### ISSUE TITLE
Can you make this a private repository?

### ISSUE THREAD

**Issue by DavePearce** [tezz99/SteamBoilerController#1]
Hi,

I would appreciate it if you can make this a private repository so that other students cannot see it in the future.  You can now do this for free on GitHub.

Cheers,

Dave

**Comment by tezz99** [comment]
Done :)

**Comment by DavePearce** [comment]
Thanks!

**Comment by DavePearce** [comment]
Hmmm, ok I can still see this one. But, not the SWEN222 Assignment 2 Cluedo one ... so something changed.
